### ISSUE TITLE
404 for search notebook

### ISSUE THREAD

**Issue by nsoft** [AllenDowney/DSIRP#1]
Got a error box when I clicked on the left side link labeled "search" 

![image](https://user-images.githubusercontent.com/3340874/146781654-76a858ae-58dc-46e0-b716-fabca96f4e9e.png)

https://github.com/AllenDowney/DSIRP/blob/main/notebooks/search2.ipynb returns 404

**Comment by AllenDowney** [comment]
I had to do some renaming, so it is now searching.ipynb.

Links to it should be updated now, but might take time to get cleared from caches.

Thanks for letting me know!
