### ISSUE TITLE
Index Problem

### ISSUE THREAD

**Issue by Jack-Kennedy-School** [AllenDowney/DSIRP#13]
where it says, "element = soup.contents[0]" it should say "element = soup.contents[1]" so that it goes to the Tag element and not the NavigableString element

**Comment by AllenDowney** [comment]
Thanks for letting me know. What file is this in?

**Comment by Jack-Kennedy-School** [comment]
the dfs notebook

**Comment by AllenDowney** [comment]
`dfs.ipynb` is currently working for me in both my development environment and Colab.

If you still think something is incorrect, please provide the information I need to replicate the error you are seeing.
