### ISSUE TITLE
Binder: Error loading AllenDowney/DSIRP/master!

### ISSUE THREAD

**Issue by aiyer-commits** [AllenDowney/DSIRP#2]
Trying to load the Algorithms Notebook:

https://mybinder.org/v2/gh/AllenDowney/DSIRP/master?urlpath=tree/algorithms.ipynb

Binder says it cannot find it!

**Comment by AllenDowney** [comment]
The notebooks are in a subdirectory called notebooks, so you might have to fix the path.

They also run in Colab if you don't want to wait for Binder to start :)

**Comment by aiyer-commits** [comment]
Ok! That link to Binder was the one at the top of the page on the book's website as well, so I imagine this issue will happen on all of the notebooks

**Comment by AllenDowney** [comment]
I didn't think I provided links to Binder. Where do you see this link? Are you using a browser extension?

**Comment by aiyer-commits** [comment]
Sorry I took so long to respond, just got back to the book and this is where I get the binder links.

![image](https://user-images.githubusercontent.com/56838551/167297458-1a4c7452-285a-4bff-9c1d-eb70047a6fb7.png)

The issue still exists, this Binder link tries to use /master, fixing the path to /main works

**Comment by aiyer-commits** [comment]
I think these links are built by Jupyter Book

**Comment by AllenDowney** [comment]
I don't see that button when I view this page; I would guess it is being generated by a browser extension.

**Comment by aiyer-commits** [comment]
I don't have any browser extensions related to jupyter or python...

**Comment by aiyer-commits** [comment]
Also changing to /main doesn't resolve the issue, Binder attempts to load it but then returns a 404: https://notebooks.gesis.org/binder/jupyter/user/allendowney-dsirp-a82pzmnc/tree/quiz01.ipynb

**Comment by aiyer-commits** [comment]
I can see the button in Google Chrome for ChromeOS and Firefox for Android

**Comment by aiyer-commits** [comment]
Also can see it on Brave for MacOS, on any page besides the introduction page

**Comment by aiyer-commits** [comment]
https://jupyterbook.org/en/stable/interactive/launchbuttons.html?highlight=binder#add-a-launch-on-binder-button

According to the docs, there is an option to add this button, but the _config.yml in the repo does not have this option... so I don't know why the button is appearing at all

**Comment by AllenDowney** [comment]
Sorry, I didn't realize it's under the rocket menu. Ok, I can replicate the problem.

I'll fix when I can, but to be honest, it's not a high priority -- I don't recommend using Binder for these notebooks.

**Comment by AllenDowney** [comment]
Thanks for looking into that.

**Comment by aiyer-commits** [comment]
https://github.com/executablebooks/jupyter-book/issues/1428

No worries! It appears that they enable this by default, this issue above says disabling it is as simple as adding an empty string to the _config.yml for the binderurl

![image](https://user-images.githubusercontent.com/56838551/167298439-47e788f8-4d1d-477f-91c4-64e0f8306c1b.png)

**Comment by aiyer-commits** [comment]
Also, it could be replaced by a colab link!

**Comment by AllenDowney** [comment]
Thanks for the PR. I will rebuild the book as soon as I can.
