### ISSUE TITLE
Algorithms Notebook Colab still pointing to /chapters

### ISSUE THREAD

**Issue by aiyer-commits** [AllenDowney/DSIRP#3]
https://colab.research.google.com/github/AllenDowney/DSIRP/blob/main/chapters/algorithms.ipynb

I changed chapters to notebooks and it works just fine!

**Comment by AllenDowney** [comment]
Where did you find this broken link?

**Comment by AllenDowney** [comment]
Never mind -- I found it. Some of the other notebooks have the same problem. Should work now.

Thanks for letting me know!
