### ISSUE TITLE
Typo on Testing Order of Growth Page

### ISSUE THREAD

**Issue by sambo55** [AllenDowney/DSIRP#4]
Thanks for all your work, enjoying the material.

I think there is a typo on Testing Order of Growth Page
'''
We’ll handle it by running over a wide range of problem sizes, hoping to sizes that run long enough to measure, but not more than a few seconds.
'''
Is hoping supposed to be hopping?

**Comment by AllenDowney** [comment]
That should be "hoping to find sizes that..."

Thanks for letting me know!
