### ISSUE TITLE
Confusing variable names in exercise

### ISSUE THREAD

**Issue by Ondross** [AllenDowney/DSIRP#5]
Hey Allen, in the recursion factorial exercise, you describe raising `x` to an integer power, but then use `n` in instructions:
![image](https://user-images.githubusercontent.com/575508/148118887-d7b373fd-018d-473d-b7f5-713f89a0ae70.png)

**Comment by AllenDowney** [comment]
Will fix. Thank you!

**Comment by AllenDowney** [comment]
Done!
